version: '3.8'

services:
  backend:
    build: ./backend  # Path to your backend code
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Bind mount to ensure code is available in the container
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

