name: Test Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job Backend
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Modifiez la version de Python selon vos besoins

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./backend  # Remplacez par le chemin de votre répertoire backend

      - name: Run backend tests
        run: pytest
        working-directory: ./backend  # Remplacez par le chemin de votre répertoire backend
